# Generated by Django 5.0.5 on 2024-05-15 20:08
from __future__ import annotations

import functools
import uuid

import django.core.serializers.json
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("webhook_uuid", models.UUIDField()),
                (
                    "topic",
                    models.CharField(help_text="Topic of the webhook event", max_length=32),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the object that triggered the webhook event",
                        max_length=32,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("PROJECT", "projects.Project")],
                        help_text="Type of the object that triggered the webhook event",
                        max_length=32,
                    ),
                ),
                (
                    "remote_ip",
                    models.GenericIPAddressField(help_text="IP address of the request client."),
                ),
                ("headers", models.JSONField(default=dict)),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        encoder=functools.partial(
                            django.core.serializers.json.DjangoJSONEncoder,
                            *(),
                            **{"indent": 2, "sort_keys": True},
                        ),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("INVALID", "Invalid"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Whether or not the webhook event has been successfully processed",
                        max_length=32,
                    ),
                ),
                ("exception", models.TextField(blank=True)),
                (
                    "traceback",
                    models.TextField(
                        blank=True,
                        help_text="Traceback if an exception was thrown during processing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhookevent",
                "ordering": ("-created",),
            },
        ),
    ]
