# Generated by Django 5.0.5 on 2024-05-16 07:21
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="object_type",
            field=models.CharField(
                choices=[("projects.Project", "projects.Project")],
                help_text="Type of the object that triggered the webhook event",
                max_length=32,
            ),
        ),
    ]
