# Generated by Django 5.0.5 on 2024-05-24 15:10
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_gristconfig_table_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gristconfig",
            name="table_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
